### ISSUE TITLE
Estimating distance using intensity

### ISSUE THREAD

**Issue by oyssolbo** [vortexntnu/acoustics#22]
The current estimate uses the power of the sound-source to estimate the distance. It is inadequite, as we often may not know the power of the sound-source beforehand.

**Comment by oyssolbo** [comment]
As of 03.01.21, the source-power is given as 177. Which unit is it given in? {W, mW, micro-W, ... }

**Comment by Areskiko** [comment]
If you're referring to line 5 in acoustics.py:
![image](https://user-images.githubusercontent.com/39183620/103622176-99143a00-4f36-11eb-8894-3bdec6654573.png)
Then it's measured in decibel as per the specifications of the pinger that were found online, searching for the model that was listed in the competition guidelines.

**Comment by oyssolbo** [comment]
But how could that be used to estimate the distance. The equation requires power in W to be valid?

**Comment by Areskiko** [comment]
I assumed [this](http://hyperphysics.phy-astr.gsu.edu/hbase/Sound/intens.html#c1) meant I could use decibels. If not we need a different approach. Although, even if we can, it's not a very good approach as it's a very rough estimate with many factors that could drastically change the result. Things like echo for instance

**Comment by oyssolbo** [comment]
Fair point. I think we can assume that they have used the proper reference-value for dB (10^(-12) W if I remember correctly) and not any other reference giving dBA, dBm etc. 

I am currently looking into the odas-library's predecessor (don't remember its name atm), as it looks like it has some nice trilateration-code

**Comment by oyssolbo** [comment]
Forgot to link to the issue before merging. Closing manually
